apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-applicationsets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/vjkancherla/PetClinic-ArgoCD-ApplicationSets-Deploy
    targetRevision: HEAD
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true