apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-production
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm-chart
    repoURL: https://github.com/vjkancherla/PetClinic-ArgoCD-ApplicationSets
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "main-10-3a15fbe7"
  destination:
    namespace: petclinic-production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
          - CreateNamespace=true
